[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.9.0"
octocrab = "0.48.0"
serde = "1.0.219"
serde_json = "1.0.142"
serde_with = "3.14.0"
tokio = {version = "1.47.1", features = ["macros", "rt-multi-thread"]}
