[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.6.0"
octocrab = "0.38.0"
serde = "1.0.204"
serde_json = "1.0.120"
serde_with = "3.9.0"
tokio = {version = "1.38.1", features = ["full"]}
