[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.10.0"
octocrab = "0.49.0"
serde = "1.0.228"
serde_json = "1.0.145"
serde_with = "3.16.1"
tokio = {version = "1.48.0", features = ["macros", "rt-multi-thread"]}

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

arbitrary_source_item_ordering    = "allow"
expect_used                       = "allow"
implicit_return                   = "allow"
missing_docs_in_private_items     = "allow"
missing_trait_methods             = "allow"
panic                             = "allow"
panic_in_result_fn                = "allow"
question_mark_used                = "allow"
ref_patterns                      = "allow"
unwrap_in_result                  = "allow"
unwrap_used                       = "allow"
wildcard_enum_match_arm           = "allow"
