[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.10.0"
octocrab = "0.48.0"
serde = "1.0.228"
serde_json = "1.0.145"
serde_with = "3.16.1"
tokio = {version = "1.48.0", features = ["macros", "rt-multi-thread"]}
