name: update_deps

on:
  workflow_dispatch: #allow manual triggering
  schedule:
      - cron: "0 4 * * 0"
jobs:
  update_deps:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
      - uses: cachix/install-nix-action@v31
      - name: setup git
        run: | 
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - uses: cachix/cachix-action@v16
        with:
          name: spicetify-nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - id: flake
        name: flake
        run: |
          set -euxo pipefail
          MESSAGE="
          flake input updates:
          $(nix flake update --no-warn-dirty 2>&1 | { grep -v 'unpacking.*' || true; } | sed '1d')"

          if [ -n "$(git diff-files 2>&1)" ]; then
            git add -A
            {
              echo "message<<EOF"
              echo "$MESSAGE"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          fi

      - id: npins
        name: npins
        run: |
          set -euxo pipefail
          MESSAGE="
          npins updates:
          $(nix run nixpkgs#npins -- --lock-file ./pkgs/npins/sources.json update -f 2>&1 | { grep '.*Changes:$\|.*revision:.*' || true; })"

          if [ -n "$(git diff-files 2>&1)" ]; then
            git add -A
            {
              echo "message<<EOF"
              echo "$MESSAGE"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          fi
      - name: fetcher
        run: |
          set -euxo pipefail
          pushd pkgs
          nix run .#fetcher
          git add generated.json
          popd
      - name: Commit and push
        run: |
          set -euxo pipefail
          MESSAGE="
          ${{ steps.flake.outputs.message }}
          ${{ steps.npins.outputs.message }}
          "
          if [[ "$MESSAGE" =~ ^[[:space:]]*$ ]]; then
            exit 0
          fi

          # Check if a small config builds
          nix build .#test

          git commit -m "CI update $(date -I)" -m "$MESSAGE"
          git push origin 'HEAD:${{ github.ref_name }}'
